# Generated by Django 3.2.4 on 2021-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='menusections',
            options={'ordering': ['name'], 'verbose_name': 'Раздел меню', 'verbose_name_plural': 'Разделы меню'},
        ),
        migrations.AlterModelOptions(
            name='restaurants',
            options={'ordering': ['name'], 'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterModelOptions(
            name='rubrics',
            options={'ordering': ['name'], 'verbose_name': 'Вид кухни', 'verbose_name_plural': 'Виды кухни'},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='menusections',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Section's name"),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=200, verbose_name="Restaurant's name"),
        ),
    ]
